USE [CRUD_SP_DB]

GO

CREATE NONCLUSTERED INDEX [NonClusteredIndex-20231102-232248] ON [dbo].[ProductInfo_Tab]
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF)

GO
