USE [master]
GO
/****** Object:  Database [CRUD_SP_DB]    Script Date: 8/9/2024 7:31:33 PM ******/
CREATE DATABASE [CRUD_SP_DB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CRUD_SP_DB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\CRUD_SP_DB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CRUD_SP_DB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQL2022\MSSQL\DATA\CRUD_SP_DB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CRUD_SP_DB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CRUD_SP_DB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CRUD_SP_DB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CRUD_SP_DB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CRUD_SP_DB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CRUD_SP_DB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET RECOVERY FULL 
GO
ALTER DATABASE [CRUD_SP_DB] SET  MULTI_USER 
GO
ALTER DATABASE [CRUD_SP_DB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CRUD_SP_DB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CRUD_SP_DB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CRUD_SP_DB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CRUD_SP_DB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CRUD_SP_DB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CRUD_SP_DB', N'ON'
GO
ALTER DATABASE [CRUD_SP_DB] SET QUERY_STORE = ON
GO
ALTER DATABASE [CRUD_SP_DB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [CRUD_SP_DB]
GO
/****** Object:  Table [dbo].[ProductInfo_Tab]    Script Date: 8/9/2024 7:31:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductInfo_Tab](
	[ProductID] [int] NOT NULL,
	[ItemName] [nvarchar](50) NULL,
	[Color] [nvarchar](50) NULL,
	[Status] [nvarchar](50) NULL,
	[ExpiryData] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ProductID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  StoredProcedure [dbo].[SP_Product_Delete]    Script Date: 8/9/2024 7:31:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE   PROC [dbo].[SP_Product_Delete]
@ProductID int
as 
begin
delete ProductInfo_Tab where ProductID=@ProductID
end
GO
/****** Object:  StoredProcedure [dbo].[SP_Product_Insert]    Script Date: 8/9/2024 7:31:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE PROC [dbo].[SP_Product_Insert]
@ProductID int,
@ItemName nvarchar(50),
@Color nvarchar(50),
@Status nvarchar(50),
@ExpiryDate datetime 
as 
begin
insert into ProductInfo_Tab (ProductID,ItemName,Color,Status,ExpiryData) values
(@ProductID,@ItemName,@Color,@Status,@ExpiryDate)
end


GO
/****** Object:  StoredProcedure [dbo].[SP_Product_Search]    Script Date: 8/9/2024 7:31:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



CREATE   PROC [dbo].[SP_Product_Search]
@ProductID int
as 
begin
SELECT * FROM ProductInfo_Tab where ProductID=@ProductID
end
GO
/****** Object:  StoredProcedure [dbo].[SP_Product_Update]    Script Date: 8/9/2024 7:31:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE   PROC [dbo].[SP_Product_Update]
@ProductID int,
@ItemName nvarchar(50),
@Color nvarchar(50),
@Status nvarchar(50),
@ExpiryDate datetime 
as 
begin
update  ProductInfo_Tab set 
ItemName=@ItemName,Color=@Color,Status=@Status,ExpiryData=@ExpiryDate where ProductID=@ProductID
end

GO
/****** Object:  StoredProcedure [dbo].[SP_Product_View]    Script Date: 8/9/2024 7:31:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROC [dbo].[SP_Product_View]
as 
begin
SELECT * FROM ProductInfo_Tab
end


GO
USE [master]
GO
ALTER DATABASE [CRUD_SP_DB] SET  READ_WRITE 
GO
